2022-12-29 08:58:38,127 (96187/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-29 08:58:38,127 (96187/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-12-29 08:58:38,130 (96187/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2022-12-29 08:59:17,279 (96273/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-29 08:59:17,279 (96273/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-12-29 08:59:20,545 (96273/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  password authentication failed for user "postgres"\n'
2022-12-29 08:59:23,538 (96294/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-29 08:59:23,538 (96294/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-12-29 08:59:26,805 (96294/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  password authentication failed for user "postgres"\n'
2022-12-29 08:59:36,072 (96330/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-29 08:59:36,072 (96330/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-12-29 09:01:04,679 (96330/MainThread) pgcli.pgexecute ERROR - sql: 'select *\nfrom orders', error: UndefinedTable('relation "orders" does not exist\nLINE 2: from orders\n             ^')
2022-12-29 09:01:04,681 (96330/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "orders" does not exist\nLINE 2: from orders\n             ^\n'
2022-12-29 09:01:31,320 (96412/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-29 09:01:31,320 (96412/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-12-29 09:07:17,018 (96412/MainThread) pgcli.pgexecute ERROR - sql: 'select *\nfrom orders o\njoin delivery_point dp on o.order_id = dp.order_id\njoin address a', error: SyntaxError('syntax error at end of input\nLINE 4: join address a\n                      ^')
2022-12-29 09:07:17,020 (96412/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 4: join address a\n                      ^\n'
